In [1]:
#Soal 1
#Buatlah identitas diri menggunakan pemograman python sederhana

Nama = 'Aurel Elviolita Putri'
TTL = 'Bekasi, 15 juli 2002'
Fakultas = 'Ilmu Komputer'
Prodi = 'Teknik Informatika'
Angktn = '2021'

print("Nama : ", Nama)
print("Tempat, Tanggal lahir : " , TTL)
print("Fakultas : " , Fakultas)
print("Program Studi : " , Prodi)
print("Angkatan : " , Angktn)


Nama :  Aurel Elviolita Putri
Tempat, Tanggal lahir :  Bekasi, 15 juli 2002
Fakultas :  Ilmu Komputer
Program Studi :  Teknik Informatika
Angkatan :  2021


In [2]:
# Soal 2
# Buatlah matriksC dengan orde 2x3, dan nilai yang diberikan pada matriksC adalah sebagai berikut:

    # Baris 1 Kolom 1, nilai = 1
    # Baris 1 Kolom 2, nilai = 2
    # Baris 1 Kolom 3, nilai = 3
    # Baris 2 Kolom 1, nilai = 4
    # Baris 2 Kolom 2, nilai = 5
    # Baris 2 Kolom 3, nilai = 6

matriksC = [[1,2,3],[4,5,6]]
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


In [3]:
# Soal 3
# Buatlah matriks dengan orde 3x2, dengan nilai adalah:

    # Baris 1 Kolom 1, nilai = 2
    # Baris 1 Kolom 2, nilai = 2
    # Baris 2 Kolom 1, nilai = 2
    # Baris 2 Kolom 2, nilai = 2
    # Baris 3 Kolom 1, nilai = 2
    # Baris 3 Kolom 2, nilai = 2

matriks = [[2,2],[2,2],[2,2]]
print(matriks)

[[2, 2], [2, 2], [2, 2]]


In [4]:
# Soal 4 dan 5
#import lah library Numpy
''' Dengan memanfaatkan library numpy Buatlah matriks dengan menggunakan 
Library Numpy dengan panjang elemen adalah 32 dan matriks memiliki orde 4x8'''

import numpy as np

# Membuat array 1D dengan panjang elemen 32
array_1d = np.arange(32)

# Mengubah array 1D menjadi matriks 4x8
matriks_4x8 = np.reshape(array_1d, (4, 8))

# Menampilkan matriks
print(matriks_4x8)



[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [5]:
# Soal 6

import numpy as np

# Membuat matriks 3x30 dengan nilai elemen acak dari 1 sampai 5
matriks_3x30 = np.random.randint(1, 6, size=(3, 30))

# Menampilkan matriks
print(matriks_3x30)


[[1 3 1 3 2 5 2 4 1 1 3 5 4 4 5 2 3 5 5 1 5 1 4 4 3 3 2 2 4 4]
 [1 3 5 5 1 5 4 5 4 3 1 4 1 3 4 1 5 3 1 4 4 1 3 4 4 1 5 1 4 3]
 [5 3 4 4 2 5 2 3 4 5 1 4 2 3 3 3 3 3 1 1 1 1 1 3 1 2 5 4 2 1]]
